name: GH Pages Deployment
on: push
permissions:
   contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.build-status.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing NPM packages
        run: npm ci

      - name: Building project
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v4.4.3
        with:
          name: production-files
          path: ./build

      - name: Set build status
        id: build-status
        run: echo "Build completed"
    
  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Report build status
        run: |
          if [ "${{ needs.build.result }}" == "success" ]; then
            echo "Build was successful!"
          else
            echo "Build failed!"
          fi

  deploy:
    name: Deploy
    needs: build
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: production-files
          path: ./build

      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Display GitHub Pages URL
        run: echo "Your application is live at: https://<username>.github.io/<repository-name>/"
