name: deploy react app
on: push
permissions:
    contents: write 
jobs: 
  deploy-react-app:
    runs-on: ubuntu-latest
    steps: 
      - name: clone the repository
        uses: actions/checkout@v4

      - name: set node options to support legacy OpenSSL
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
      - name: install npm packages
        run: npm install
      
      - name: run npm
        run: npm run build
      
      - name: test npm
        run: npm run test
      
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      
